language: c
compiler: gcc
before_install:
 - sudo add-apt-repository ppa:vala-team/ppa -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq gnome-common libglib2.0-dev libgtk-3-dev libsqlite3-dev gobject-introspection libvala-0.22-dev valac-0.22
script:
 - $(which valac)
 - valac --version
 - mkdir build && cd build
 - cmake ..
 - make
